name: CI

on:
  push:
    branches:
      - main
      - tmp
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Fmt
        run: zig fmt . --check
        if: matrix.os == 'ubuntu-latest'

      - name: Run Tests
        run: zig build test
